export type Category = 'Music' | 'Culture' | 'Nature' | 'Food' | 'Seasonal' | 'Art';
export type Mood = 'Energetic' | 'Spiritual' | 'Romantic' | 'Family' | 'Adventure' | 'Chill';

export interface Review {
  author: string;
  avatar: string;
  date: string;
  rating: number;
  comment: string;
}

export interface Festival {
  id: string;
  name: string;
  nameKo?: string;
  country: string;
  city: string;
  countryCode: string;
  month: string;
  duration: string;
  category: Category;
  mood: Mood[];
  image: string;
  heroImage: string;
  description: string;
  shortDesc: string;
  rating: number;
  reviewCount: number;
  featured: boolean;
  editorsPick: boolean;
  tags: string[];
  reviews: Review[];
}

export const festivals: Festival[] = [
  // --- DOMESTIC (Korea) ---
  {
    id: 'jinju-lantern',
    name: 'Jinju Lantern Festival',
    nameKo: '진주 남강 유등축제',
    country: 'South Korea',
    city: 'Jinju',
    countryCode: 'KR',
    month: 'October',
    duration: '10 days',
    category: 'Culture',
    mood: ['Romantic', 'Family', 'Chill'],
    image: 'https://images.unsplash.com/photo-1600298882525-15f34e3d70ca?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1600298882525-15f34e3d70ca?w=1600&q=80',
    description: 'Thousands of luminous lanterns float down the Nam River, casting a golden glow across the night sky. This 400-year-old tradition commemorates the battle of Jinju, transforming the city into a breathtaking sea of light every autumn.',
    shortDesc: 'Thousands of lanterns illuminate the Nam River in this 400-year-old tradition.',
    rating: 4.9,
    reviewCount: 1842,
    featured: true,
    editorsPick: true,
    tags: ['Lanterns', 'Night', 'River', 'Traditional'],
    reviews: [
      { author: 'Ji-won Lee', avatar: 'https://i.pravatar.cc/60?img=1', date: 'Oct 2024', rating: 5, comment: 'One of the most magical nights of my life. The lanterns reflecting on the water are beyond words.' },
      { author: 'Sarah M.', avatar: 'https://i.pravatar.cc/60?img=2', date: 'Oct 2024', rating: 5, comment: 'Absolutely spectacular. Bring a good camera — you\'ll want to capture every moment.' },
    ],
  },
  {
    id: 'boryeong-mud',
    name: 'Boryeong Mud Festival',
    nameKo: '보령 머드축제',
    country: 'South Korea',
    city: 'Boryeong',
    countryCode: 'KR',
    month: 'July',
    duration: '10 days',
    category: 'Culture',
    mood: ['Energetic', 'Family', 'Adventure'],
    image: 'https://images.unsplash.com/photo-1564419320408-38e88b48956e?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1564419320408-38e88b48956e?w=1600&q=80',
    description: 'Dive into the world\'s most beloved mud festival on Daecheon Beach. With over 2 million visitors each year, this playful celebration lets you bathe in mineral-rich Boryeong mud while enjoying concerts and beach activities.',
    shortDesc: 'Millions dive into mineral-rich mud at this legendary beach festival.',
    rating: 4.6,
    reviewCount: 2341,
    featured: false,
    editorsPick: false,
    tags: ['Beach', 'Summer', 'Interactive', 'Unique'],
    reviews: [
      { author: 'Tom K.', avatar: 'https://i.pravatar.cc/60?img=3', date: 'Jul 2024', rating: 4, comment: 'Hilarious, messy, and totally worth it. Don\'t wear anything you love!' },
    ],
  },
  {
    id: 'andong-mask',
    name: 'Andong Mask Dance Festival',
    nameKo: '안동 탈춤 페스티벌',
    country: 'South Korea',
    city: 'Andong',
    countryCode: 'KR',
    month: 'September',
    duration: '9 days',
    category: 'Art',
    mood: ['Spiritual', 'Family', 'Chill'],
    image: 'https://images.unsplash.com/photo-1574236170880-6cd25f04d83e?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1574236170880-6cd25f04d83e?w=1600&q=80',
    description: 'The world\'s largest gathering of mask dance performances takes place in the heart of Korea\'s traditional culture capital. Ancient folk dances, vibrant costumes, and Hahoe Village provide an unforgettable journey into Korean heritage.',
    shortDesc: 'Ancient folk dances and traditional masks unite in Korea\'s culture capital.',
    rating: 4.8,
    reviewCount: 1203,
    featured: true,
    editorsPick: true,
    tags: ['Traditional', 'Dance', 'Heritage', 'Folk'],
    reviews: [
      { author: 'Minho P.', avatar: 'https://i.pravatar.cc/60?img=4', date: 'Sep 2024', rating: 5, comment: 'Deeply moving. The Hahoe village backdrop makes it feel like time travel.' },
    ],
  },
  {
    id: 'hwacheon-trout',
    name: 'Hwacheon Sancheoneo Ice Festival',
    nameKo: '화천 산천어축제',
    country: 'South Korea',
    city: 'Hwacheon',
    countryCode: 'KR',
    month: 'January',
    duration: '20 days',
    category: 'Nature',
    mood: ['Family', 'Adventure', 'Chill'],
    image: 'https://images.unsplash.com/photo-1548777123-e216912df7d8?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1548777123-e216912df7d8?w=1600&q=80',
    description: 'Ice fishing on a frozen river, sledding, and catching mountain trout with bare hands — this beloved winter festival draws over a million visitors to the snow-covered mountains of Gangwon Province each January.',
    shortDesc: 'Ice fishing and winter fun on frozen rivers in snowy Gangwon Province.',
    rating: 4.7,
    reviewCount: 3102,
    featured: false,
    editorsPick: false,
    tags: ['Winter', 'Ice Fishing', 'Snow', 'Family'],
    reviews: [
      { author: 'Emma J.', avatar: 'https://i.pravatar.cc/60?img=5', date: 'Jan 2024', rating: 5, comment: 'Catching fish with my bare hands through an ice hole — absolutely unforgettable!' },
    ],
  },
  {
    id: 'busan-fireworks',
    name: 'Busan International Fireworks Festival',
    nameKo: '부산 불꽃축제',
    country: 'South Korea',
    city: 'Busan',
    countryCode: 'KR',
    month: 'October',
    duration: '1 day',
    category: 'Culture',
    mood: ['Romantic', 'Family', 'Energetic'],
    image: 'https://images.unsplash.com/photo-1627844718626-4b68fbab6a62?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1627844718626-4b68fbab6a62?w=1600&q=80',
    description: 'Asia\'s greatest fireworks spectacle lights up Gwangalli Beach for one dazzling night. Synchronized pyrotechnics from teams across 8 countries explode above the ocean, with Gwangan Bridge as the ultimate backdrop.',
    shortDesc: 'Asia\'s greatest fireworks spectacle above Busan\'s iconic Gwangan Bridge.',
    rating: 4.8,
    reviewCount: 4521,
    featured: false,
    editorsPick: true,
    tags: ['Fireworks', 'Beach', 'Night', 'Spectacular'],
    reviews: [
      { author: 'Alex R.', avatar: 'https://i.pravatar.cc/60?img=6', date: 'Oct 2024', rating: 5, comment: 'The best fireworks I\'ve ever seen. The bridge reflection on the water is insane.' },
    ],
  },

  // --- INTERNATIONAL ---
  {
    id: 'coachella',
    name: 'Coachella Valley Music & Arts Festival',
    country: 'United States',
    city: 'Indio, California',
    countryCode: 'US',
    month: 'April',
    duration: '3 weekends',
    category: 'Music',
    mood: ['Energetic', 'Chill', 'Romantic'],
    image: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=1600&q=80',
    description: 'The world\'s most iconic music festival transforms the Coachella Valley into a utopia of art, fashion, and sound. With 160,000 attendees per weekend, headliners from every genre, and jaw-dropping art installations, Coachella is a cultural phenomenon.',
    shortDesc: 'The world\'s most iconic music festival — art, fashion, and sound in the desert.',
    rating: 4.7,
    reviewCount: 18432,
    featured: true,
    editorsPick: true,
    tags: ['Music', 'Art', 'Desert', 'Fashion', 'Festival'],
    reviews: [
      { author: 'Maya T.', avatar: 'https://i.pravatar.cc/60?img=7', date: 'Apr 2024', rating: 5, comment: 'Mind-blowing. The art installations alone are worth the trip.' },
      { author: 'James L.', avatar: 'https://i.pravatar.cc/60?img=8', date: 'Apr 2024', rating: 4, comment: 'Amazing music, but be prepared for the crowds and heat. Go in weekend 2 for better vibes.' },
    ],
  },
  {
    id: 'rio-carnival',
    name: 'Rio Carnival',
    country: 'Brazil',
    city: 'Rio de Janeiro',
    countryCode: 'BR',
    month: 'February',
    duration: '5 days',
    category: 'Culture',
    mood: ['Energetic', 'Romantic', 'Adventure'],
    image: 'https://images.unsplash.com/photo-1551887196-72e32bfc7bf3?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1551887196-72e32bfc7bf3?w=1600&q=80',
    description: 'The world\'s largest carnival erupts in Rio each February. Two million people per day take to the streets for samba parades, elaborate costumes, and non-stop music in one of the greatest parties on Earth.',
    shortDesc: 'Two million people daily — the world\'s largest and most spectacular carnival.',
    rating: 4.9,
    reviewCount: 22187,
    featured: true,
    editorsPick: true,
    tags: ['Samba', 'Parade', 'Costumes', 'Dance', 'Vibrant'],
    reviews: [
      { author: 'Carlos M.', avatar: 'https://i.pravatar.cc/60?img=9', date: 'Feb 2024', rating: 5, comment: 'You have to experience this at least once in your life. Words can\'t do it justice.' },
    ],
  },
  {
    id: 'glastonbury',
    name: 'Glastonbury Festival',
    country: 'United Kingdom',
    city: 'Pilton, Somerset',
    countryCode: 'GB',
    month: 'June',
    duration: '5 days',
    category: 'Music',
    mood: ['Energetic', 'Chill', 'Adventure'],
    image: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=1600&q=80',
    description: 'The legendary Worthy Farm transforms into the world\'s greatest music festival for five days each June. With 200,000 attendees, hundreds of stages, and an unmatched lineup, Glastonbury is the pinnacle of festival culture.',
    shortDesc: 'The world\'s greatest music festival — 200,000 people, hundreds of stages.',
    rating: 4.8,
    reviewCount: 15632,
    featured: false,
    editorsPick: true,
    tags: ['Music', 'Camping', 'UK', 'Legendary', 'Headline'],
    reviews: [
      { author: 'Hannah B.', avatar: 'https://i.pravatar.cc/60?img=10', date: 'Jun 2024', rating: 5, comment: 'Even the mud can\'t dampen the magic of Glastonbury. Absolute dream.' },
    ],
  },
  {
    id: 'burning-man',
    name: 'Burning Man',
    country: 'United States',
    city: 'Black Rock City, Nevada',
    countryCode: 'US',
    month: 'August',
    duration: '9 days',
    category: 'Art',
    mood: ['Spiritual', 'Adventure', 'Energetic'],
    image: 'https://images.unsplash.com/photo-1533669955142-6a73332af4db?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1533669955142-6a73332af4db?w=1600&q=80',
    description: 'A temporary city of 80,000 rises from the Nevada desert for one extraordinary week of radical self-expression, participatory art, and community. No money, no spectators — only participants in one of the world\'s most transformative gatherings.',
    shortDesc: 'A city of 80,000 in the Nevada desert — radical art, community, transformation.',
    rating: 4.6,
    reviewCount: 8934,
    featured: false,
    editorsPick: false,
    tags: ['Art', 'Desert', 'Community', 'Unique', 'Transformative'],
    reviews: [
      { author: 'Zara W.', avatar: 'https://i.pravatar.cc/60?img=11', date: 'Aug 2024', rating: 5, comment: 'Changed my life. Not a festival — a full community experience.' },
    ],
  },
  {
    id: 'holi',
    name: 'Holi — Festival of Colors',
    country: 'India',
    city: 'Mathura & Vrindavan',
    countryCode: 'IN',
    month: 'March',
    duration: '2 days',
    category: 'Seasonal',
    mood: ['Energetic', 'Spiritual', 'Family'],
    image: 'https://images.unsplash.com/photo-1567591370428-3e9e0def2e84?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1567591370428-3e9e0def2e84?w=1600&q=80',
    description: 'The ancient Hindu festival of spring erupts in a riot of color as millions throw vibrant powder and water across India. Nowhere is it celebrated more joyfully than in Mathura and Vrindavan, the birthplace of Lord Krishna.',
    shortDesc: 'Millions celebrate spring by throwing vibrant colored powder across India.',
    rating: 4.9,
    reviewCount: 31204,
    featured: true,
    editorsPick: true,
    tags: ['Color', 'Spring', 'Hindu', 'Joy', 'India'],
    reviews: [
      { author: 'Priya S.', avatar: 'https://i.pravatar.cc/60?img=12', date: 'Mar 2024', rating: 5, comment: 'Pure joy. You leave covered in every color imaginable — and smiling all day.' },
    ],
  },
  {
    id: 'oktoberfest',
    name: 'Oktoberfest',
    country: 'Germany',
    city: 'Munich',
    countryCode: 'DE',
    month: 'September',
    duration: '16 days',
    category: 'Food',
    mood: ['Energetic', 'Family', 'Chill'],
    image: 'https://images.unsplash.com/photo-1534430480872-3498386e7856?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1534430480872-3498386e7856?w=1600&q=80',
    description: 'Six million liters of Bavarian beer, traditional pretzels, oompah bands, and dirndls — Munich\'s Oktoberfest is the world\'s largest folk festival. Every September, 6 million visitors pack the Theresienwiese fairgrounds for 16 days of celebration.',
    shortDesc: 'The world\'s largest folk festival — 6 million liters of Bavarian beer.',
    rating: 4.7,
    reviewCount: 19823,
    featured: false,
    editorsPick: false,
    tags: ['Beer', 'Bavaria', 'Food', 'Folk', 'Germany'],
    reviews: [
      { author: 'Klaus H.', avatar: 'https://i.pravatar.cc/60?img=13', date: 'Sep 2024', rating: 5, comment: 'Ein Prosit! The atmosphere inside the beer tents is electric. Reserve your table early.' },
    ],
  },
  {
    id: 'cherry-blossom-japan',
    name: 'Cherry Blossom Festival (Hanami)',
    country: 'Japan',
    city: 'Tokyo & Kyoto',
    countryCode: 'JP',
    month: 'March–April',
    duration: '2 weeks',
    category: 'Nature',
    mood: ['Romantic', 'Family', 'Chill', 'Spiritual'],
    image: 'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1600&q=80',
    description: 'Japan\'s most beloved tradition — gathering under cherry blossom trees for hanami (flower viewing) picnics. Each spring, millions of pink blooms transform parks, riverbanks, and castle grounds into ethereal pink canopies for just two fleeting weeks.',
    shortDesc: 'Japan\'s ethereal pink canopy — hanami picnics under ancient cherry blossoms.',
    rating: 4.9,
    reviewCount: 28764,
    featured: true,
    editorsPick: true,
    tags: ['Cherry Blossom', 'Spring', 'Sakura', 'Nature', 'Japan'],
    reviews: [
      { author: 'Yuki N.', avatar: 'https://i.pravatar.cc/60?img=14', date: 'Apr 2024', rating: 5, comment: 'Ueno Park at golden hour during peak bloom — nothing compares.' },
    ],
  },
  {
    id: 'la-tomatina',
    name: 'La Tomatina',
    country: 'Spain',
    city: 'Buñol, Valencia',
    countryCode: 'ES',
    month: 'August',
    duration: '1 day',
    category: 'Culture',
    mood: ['Energetic', 'Adventure', 'Family'],
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=1600&q=80',
    description: 'Every last Wednesday of August, the small Spanish town of Buñol becomes the stage for the world\'s biggest food fight. Participants hurl 150,000 tomatoes at each other in a gloriously messy, hour-long battle of pure joy.',
    shortDesc: '150,000 tomatoes fly through the air in the world\'s greatest food fight.',
    rating: 4.5,
    reviewCount: 7234,
    featured: false,
    editorsPick: false,
    tags: ['Spain', 'Tomatoes', 'Unique', 'Fun', 'Food Fight'],
    reviews: [
      { author: 'Lucia G.', avatar: 'https://i.pravatar.cc/60?img=15', date: 'Aug 2024', rating: 4, comment: 'Absolutely chaotic in the best possible way. Wear old clothes!' },
    ],
  },
  {
    id: 'diwali',
    name: 'Diwali — Festival of Lights',
    country: 'India',
    city: 'Jaipur & Varanasi',
    countryCode: 'IN',
    month: 'October–November',
    duration: '5 days',
    category: 'Seasonal',
    mood: ['Spiritual', 'Family', 'Romantic'],
    image: 'https://images.unsplash.com/photo-1605278407197-a9e00b9ed6d9?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1605278407197-a9e00b9ed6d9?w=1600&q=80',
    description: 'The Festival of Lights illuminates all of India for five magical days. Millions of oil lamps (diyas), fireworks, and rangoli patterns celebrate the triumph of light over darkness across temples, palaces, and every household.',
    shortDesc: 'Millions of oil lamps illuminate India in the triumph of light over darkness.',
    rating: 4.9,
    reviewCount: 24503,
    featured: false,
    editorsPick: true,
    tags: ['Lights', 'Spiritual', 'India', 'Diwali', 'Fireworks'],
    reviews: [
      { author: 'Ananya R.', avatar: 'https://i.pravatar.cc/60?img=16', date: 'Nov 2024', rating: 5, comment: 'Varanasi during Diwali is otherworldly. The ghats covered in diyas is a sight I\'ll never forget.' },
    ],
  },
  {
    id: 'edinburgh-fringe',
    name: 'Edinburgh Festival Fringe',
    country: 'United Kingdom',
    city: 'Edinburgh, Scotland',
    countryCode: 'GB',
    month: 'August',
    duration: '25 days',
    category: 'Art',
    mood: ['Chill', 'Adventure', 'Family'],
    image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=1600&q=80',
    description: 'The world\'s largest arts festival transforms Edinburgh every August, with over 3,000 shows in 300 venues across 25 extraordinary days. Comedy, theatre, dance, circus, and cabaret fill every corner of this magnificent Scottish capital.',
    shortDesc: '3,000 shows in 25 days — the world\'s largest arts festival transforms Edinburgh.',
    rating: 4.8,
    reviewCount: 11234,
    featured: false,
    editorsPick: false,
    tags: ['Theatre', 'Comedy', 'Art', 'Scotland', 'Performance'],
    reviews: [
      { author: 'Fiona M.', avatar: 'https://i.pravatar.cc/60?img=17', date: 'Aug 2024', rating: 5, comment: 'Impossible to see everything you want to. That\'s the beauty of it.' },
    ],
  },
  {
    id: 'songkran',
    name: 'Songkran Water Festival',
    country: 'Thailand',
    city: 'Chiang Mai & Bangkok',
    countryCode: 'TH',
    month: 'April',
    duration: '3 days',
    category: 'Culture',
    mood: ['Energetic', 'Family', 'Adventure'],
    image: 'https://images.unsplash.com/photo-1504214208698-ea1916a2195a?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1504214208698-ea1916a2195a?w=1600&q=80',
    description: 'Thailand\'s traditional New Year becomes the world\'s biggest water fight. Every April, the streets of Chiang Mai and Bangkok become giant arenas where millions drench each other with water guns and hoses in joyful celebration.',
    shortDesc: 'Thailand\'s New Year — the world\'s biggest water fight floods the streets.',
    rating: 4.7,
    reviewCount: 13876,
    featured: false,
    editorsPick: false,
    tags: ['Water', 'Thailand', 'New Year', 'Fun', 'Street Party'],
    reviews: [
      { author: 'Mike T.', avatar: 'https://i.pravatar.cc/60?img=18', date: 'Apr 2024', rating: 5, comment: 'Chiang Mai during Songkran is the most fun I\'ve ever had getting completely soaked.' },
    ],
  },
  {
    id: 'notting-hill-carnival',
    name: 'Notting Hill Carnival',
    country: 'United Kingdom',
    city: 'London',
    countryCode: 'GB',
    month: 'August',
    duration: '2 days',
    category: 'Music',
    mood: ['Energetic', 'Family', 'Adventure'],
    image: 'https://images.unsplash.com/photo-1520986606214-8b456906c813?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1520986606214-8b456906c813?w=1600&q=80',
    description: 'Europe\'s largest street festival celebrates Caribbean culture in the heart of London. Over two million people join the extravagant parade, dancing to the boom of sound systems and feasting on jerk chicken and roti on every corner.',
    shortDesc: 'Europe\'s largest street festival — 2 million people celebrate Caribbean culture in London.',
    rating: 4.6,
    reviewCount: 9823,
    featured: false,
    editorsPick: false,
    tags: ['Caribbean', 'London', 'Street', 'Music', 'Dance'],
    reviews: [
      { author: 'Jasmine C.', avatar: 'https://i.pravatar.cc/60?img=19', date: 'Aug 2024', rating: 5, comment: 'The costumes, the food, the music — London at its absolute best.' },
    ],
  },
  {
    id: 'day-of-dead',
    name: 'Día de los Muertos',
    country: 'Mexico',
    city: 'Oaxaca & Mexico City',
    countryCode: 'MX',
    month: 'November',
    duration: '3 days',
    category: 'Seasonal',
    mood: ['Spiritual', 'Family', 'Romantic'],
    image: 'https://images.unsplash.com/photo-1518105779142-d975f22f1b0a?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1518105779142-d975f22f1b0a?w=1600&q=80',
    description: 'Mexico\'s most soulful celebration honors the deceased with marigold-carpeted altars, skull face paint, candlelit cemetery vigils, and joyful processions. The UNESCO-recognized tradition transforms death into a vibrant, colorful reunion.',
    shortDesc: 'Marigolds and skull paint honor the dead in Mexico\'s most soulful celebration.',
    rating: 4.9,
    reviewCount: 15672,
    featured: true,
    editorsPick: true,
    tags: ['Mexico', 'Spiritual', 'Colorful', 'UNESCO', 'Tradition'],
    reviews: [
      { author: 'Sofia A.', avatar: 'https://i.pravatar.cc/60?img=20', date: 'Nov 2024', rating: 5, comment: 'Deeply moving. Not morbid at all — joyful and beautiful. Oaxaca at night is magical.' },
    ],
  },
];

export const getFeaturedFestivals = () => festivals.filter(f => f.featured);
export const getEditorsPick = () => festivals.filter(f => f.editorsPick);
export const getByCategory = (category: Category) => festivals.filter(f => f.category === category);
export const getByMood = (mood: Mood) => festivals.filter(f => f.mood.includes(mood));
export const getFestivalById = (id: string) => festivals.find(f => f.id === id);

export const categories: Category[] = ['Music', 'Culture', 'Nature', 'Food', 'Seasonal', 'Art'];
export const moods: Mood[] = ['Energetic', 'Spiritual', 'Romantic', 'Family', 'Adventure', 'Chill'];
